[workspace]
resolver = "2"
members = [
    "src/foo",
    "src/member1"
]
default-members = ["src/foo"]

[workspace.package]
edition = "2021"
version = "1.0.0"

[workspace.dependencies]
member1 = { path="./src/member1" }
member2 = { path="subprojects/member2-1.0", features = ["f1"] }
